name: environment variables in multiple levels

on:
  push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    
    steps:
   
     -name: checkout repo
      uses: actions/checkout@v4
    
     -name: install cowsay program 
      run:cowsay -f dragon "run for cover">>dragon.txt

     -name: test file exists
      run: grep -i "dragon"dragon.txt

     -name: list repo files
      run: ls -ltra    